### ISSUE TITLE
Transition 'ballistic2Back' not implemented

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown-Client#1093]
First referenced [back in 2013](https://github.com/Zarel/Pokemon-Showdown-Client/blob/b16c1527daf8bd23fb378dfdfb7b7b01aa7edb0e/data/graphics.js#L175)

There is a [ballistic2Under](https://github.com/Zarel/Pokemon-Showdown-Client/blob/b16c1527daf8bd23fb378dfdfb7b7b01aa7edb0e/js/battle.js#L661-L665), however.

**Comment by Zarel** [comment]
Well, Ridaz has since quit PS.

`ballistic2Back`, judging from its name, is supposed to do the exact same thing as `ballistic2` – show a parabolic arc.

In the past, we used an algorithm that required us to explicitly specify if ballistic trajectories went backward or forward. But it was rendered unnecessary with an engine update (and `ballisticBack` replaced with `ballistic`). It seems like we just forgot to do the same thing with `ballistic2` and `ballistic2Back`.

**Comment by Zarel** [comment]
Apparently `ballistic2` goes under when going backwards? And so does `ballistic2Under`. I'm so confused.
