### ISSUE TITLE
Its urgent! About virtual bullying and IPs

### ISSUE THREAD

**Issue by DaniellMesquita** [Zarel/Pokemon-Showdown-Client#1165]
I had a discussion with a mod, an he just banned a user.
But that user practiced virtual bullying and incentive to suicide, and a ban doesn't resolves it.
I'll take this case virtual crimes police, but I need your help @Zarel 
For which hours/days a IP associated to a username is stored?
Please urgently store the IP of "negroemerda", but I don't want you to send it to me, store it for consulting
Could you increase the IP log storage, available for judicial claims?
![image](https://user-images.githubusercontent.com/6765277/48731327-ee404500-ec23-11e8-9c8c-1cb0dfa8fc94.png)

**Comment by xfix** [comment]
lol

**Comment by xfix** [comment]
Seriously however, Pokemon Showdown GitHub bug tracker is for technical issues only.

Also, according to our privacy policy, we cannot provide an IP address to you. We are willing to provide it to a police however, if they contact us however.

**Comment by DaniellMesquita** [comment]
> Seriously however, Pokemon Showdown GitHub bug tracker is for technical issues only.
> 
> Also, according to our privacy policy, we cannot provide an IP address to you. We are willing to provide it to a police however, if they contact us however.

You'd replied only after 9 minutes after closing the issue, starting the message with "Seriously however". Then, do you mean now you're serious, and therefore has been joking?

As clearly I see, you didn't read at the issue:
> GitHub bug tracker is for technical issues only.

Storing IPs is a technical issue.

> according to our privacy policy, we cannot provide an IP address to you

Please try to point in which phrase of my issue/comments, I said that I want the IP?

> We are willing to provide it to a police however, if they contact us however.

How? The Pokémon Showdown's global moderator and Portuguese room's owner "Andy >_>" said that IPs associated to usernames are stored for about 2 hours.

**Comment by Zarel** [comment]
@DaniellMesquita This is the second time you've argued with project staff about really basic things. It's clear you don't know how to use GitHub. You're now blocked.

**Comment by Zarel** [comment]
This is the first time I've blocked anyone who wasn't a spammer I reported to GitHub, and also wasn't a mistaken pull request I blocked to prevent mistakes with a message of "feel free to e-mail us to get unblocked if you ever want to intentionally interact with us".

So, some clarification and reassurance:

The only things that belong in a GitHub issue:

1. Bugs and flaws in the code (other than mechanics bugs, which should go through Bug Reports for vetting)
2. Planned features (we don't really have a set policy for feature requests currently; I don't like them but I've been keeping them open)

This list does _not_ include questions, technical or otherwise (unless you can spin it as a bug/feature, like "documentation should answer this question").

If you create a mistaken issue or pull request, we will just close it and direct you to the right place. We'll also usually answer your question, just to be nice. We're generally pretty forgiving of mistakes.

Tech support questions like this do not belong in the issue tracker, even tech support questions about programming. In general, tech support should be directed to PS's Help chatroom: https://psim.us/help

Questions about programming specifically can be directed to the Development chatroom, but keep in mind that questions about setting up side servers do not belong anywhere, and also that "how long are IPs stored" is not a programming question: https://psim.us/dev

Again, *we won't block if you mess this up.* This block today is solely because DaniellMesquita has gotten into arguments about this multiple times in the past.

**Comment by Zarel** [comment]
Unlocking in case of questions about block policy or issue policy.
