### ISSUE TITLE
Mega Charizard X outspeeds Mega Lucario with max speed

### ISSUE THREAD

**Issue by DMPS** [Zarel/Pokemon-Showdown-Client#570]
Mega charizard X's max speed is said to be 328, yet when I am in a 1v1 against it with a Mega Lucario it outspeeds even if I have max speed (355). I think it is taking lucario's speed rather than Mega's as i chose Mega in the teambuilder.

**Comment by ascriptmaster** [comment]
Turn order is decided before you mega evolve, meaning that the first turn will be based on their speed before mega evolution. Since you can't show evidence I'm assuming that's what caused the issue.

Also we have a dedicated big report thread here http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/ so don't report minor bugs here. We open issues in GitHub when we have confirmed that it's actually a bug and depending on severity.
